import argparse
import asyncio
import logging
import os
import re
from datetime import datetime
from typing import Dict, List

import httpx
import pandas as pd

from src.browser_manager import BrowserManager
from src.data_loader import DataLoader
from src.exceptions import CaptchaDetectedError, LocationVerificationError
from src.scraper import AmazonScraper


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger("AmazonRankCli")


def load_rank_tasks(args) -> List[Dict[str, str]]:
    if args.input:
        return DataLoader.load_file(args.input)

    missing = []
    if not args.marketplace:
        missing.append("--marketplace")
    if not args.zip_code:
        missing.append("--zip-code")
    if not args.asin:
        missing.append("--asin")
    if not args.keyword:
        missing.append("--keyword")

    if missing:
        raise ValueError(f"Missing required arguments for single task mode: {', '.join(missing)}")

    return [{
        "marketplace": args.marketplace,
        "zip_code": args.zip_code,
        "asin": args.asin,
        "keyword": args.keyword,
    }]


def split_asins(value: str) -> List[str]:
    return [asin.strip() for asin in re.split(r"[,\s\t\n]+", value or "") if asin.strip()]


def split_keywords(value: str) -> List[str]:
    return [keyword.strip() for keyword in re.split(r"[,\n]+", value or "") if keyword.strip()]


def save_results(results: List[Dict[str, object]]) -> str:
    os.makedirs("results", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"results/rank_results_{timestamp}.csv"

    df = pd.DataFrame(results)
    branding_row = {col: "" for col in df.columns}
    if len(df.columns) > 0:
        branding_row[df.columns[0]] = "Generated by Amazon Ranks Scrapper - consologist.com"
    df = pd.concat([df, pd.DataFrame([branding_row])], ignore_index=True)
    df.to_csv(filename, index=False)
    return filename


async def send_webhook(webhook_url: str, results: List[Dict[str, object]]):
    if not webhook_url:
        return

    payload = {
        "source": "Amazon Ranks Scrapper - consologist.com",
        "timestamp": datetime.now().isoformat(),
        "total_results": len(results),
        "results": results,
    }

    async with httpx.AsyncClient() as client:
        response = await client.post(webhook_url, json=payload)
        response.raise_for_status()


async def run(args):
    tasks = load_rank_tasks(args)
    if not tasks:
        logger.warning("No valid ranking tasks found.")
        return

    browser_manager = BrowserManager(user_data_dir=args.user_data_dir, headless=args.headless)
    scraper = AmazonScraper(browser_manager)
    all_results = []
    current_marketplace = None

    try:
        await scraper.initialize()

        for task_index, task in enumerate(tasks, start=1):
            task_marketplace = task.get("marketplace", "amazon.com") or "amazon.com"
            zip_code = task.get("zip_code", "")
            asins = split_asins(task.get("asin", ""))
            keywords = split_keywords(task.get("keyword", ""))

            logger.info(
                f"Processing task {task_index}/{len(tasks)}: "
                f"{len(keywords)} keyword(s), {len(asins)} ASIN(s), {zip_code}, {task_marketplace}"
            )

            if not zip_code or not asins or not keywords:
                logger.warning(f"Skipping task {task_index}: missing zip code, ASIN, or keyword.")
                continue

            if current_marketplace != task_marketplace:
                logger.info(f"Switching marketplace to {task_marketplace}")
                await scraper.go_to_home(task_marketplace)
                current_marketplace = task_marketplace

            for keyword in keywords:
                try:
                    logger.info(f"Searching keyword '{keyword}' for ASINs: {', '.join(asins)}")

                    await scraper.set_delivery_zip(zip_code)
                    await scraper.search_keyword(keyword)
                    results = await scraper.find_asins_ranks(asins)

                    for result in results:
                        full_result = {
                            "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                            "Marketplace": task_marketplace,
                            "Zip Code": zip_code,
                            "Keyword": keyword,
                            "ASIN": result["asin"],
                            "Sequential Rank": result["sequential_rank"] if result["found"] else "N/A",
                            "Organic Rank": result["organic_rank"] if result["found"] and result["organic_rank"] > 0 else "N/A",
                            "Sponsored Rank": result["sponsored_rank"] if result["found"] and result["sponsored_rank"] > 0 else "N/A",
                            "Is Sponsored": result.get("is_sponsored", False),
                            "Found": result["found"],
                            "Page": result["page"],
                        }
                        all_results.append(full_result)

                        if result["found"]:
                            logger.info(
                                f"Result for {result['asin']}: "
                                f"Sequential={full_result['Sequential Rank']}, "
                                f"Organic={full_result['Organic Rank']}, "
                                f"Sponsored={full_result['Sponsored Rank']}"
                            )
                        else:
                            logger.info(f"Result for {result['asin']}: Not found")

                except CaptchaDetectedError:
                    logger.error("Amazon captcha detected. Solve it in the browser, then rerun or continue manually.")
                    if args.stop_on_error:
                        return
                except LocationVerificationError as exc:
                    logger.error(f"Location error for keyword '{keyword}': {exc}")
                    if args.stop_on_error:
                        return
                except Exception as exc:
                    logger.error(f"Keyword '{keyword}' failed: {exc}", exc_info=True)
                    if args.stop_on_error:
                        return

                await asyncio.sleep(args.keyword_delay)

            await asyncio.sleep(args.task_delay)

    finally:
        if all_results:
            filename = save_results(all_results)
            logger.info(f"Results saved to {filename}")

            if args.webhook_url:
                try:
                    await send_webhook(args.webhook_url, all_results)
                    logger.info("Webhook sent successfully.")
                except Exception as exc:
                    logger.error(f"Failed to send webhook: {exc}")

        logger.info(f"Closing browser in {args.close_delay} seconds...")
        await asyncio.sleep(args.close_delay)
        await scraper.close()


def parse_args():
    parser = argparse.ArgumentParser(description="Amazon geo-rank scraper CLI")
    parser.add_argument("--input", default="", help="CSV/XLSX job file with Marketplace, Zip Code, ASIN, Keyword")
    parser.add_argument("--marketplace", default="amazon.com", help="Single task marketplace, e.g. amazon.com")
    parser.add_argument("--zip-code", default="", help="Single task delivery zip/postal code")
    parser.add_argument("--asin", default="", help="Single task ASIN or multiple ASINs separated by comma/space")
    parser.add_argument("--keyword", default="", help="Single task keyword or multiple keywords separated by comma/newline")
    parser.add_argument("--headless", action="store_true", help="Run browser in headless mode")
    parser.add_argument("--user-data-dir", default="user_data", help="Persistent browser profile directory")
    parser.add_argument("--webhook-url", default="", help="Optional webhook URL to POST JSON results")
    parser.add_argument("--keyword-delay", type=float, default=1.0, help="Seconds to wait between keywords")
    parser.add_argument("--task-delay", type=float, default=2.0, help="Seconds to wait between job rows")
    parser.add_argument("--close-delay", type=float, default=5.0, help="Seconds to keep browser open before closing")
    parser.add_argument("--stop-on-error", action="store_true", help="Stop the run on the first task/keyword error")
    return parser.parse_args()


if __name__ == "__main__":
    asyncio.run(run(parse_args()))
