import argparse
import asyncio
import logging
import os
from datetime import datetime
from typing import Dict, List

import pandas as pd

from src.browser_manager import BrowserManager
from src.detail_scraper import AmazonDetailScraper
from src.exceptions import CaptchaDetectedError, LocationVerificationError


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger("AmazonDetailPageMain")


def load_detail_tasks(args) -> List[Dict[str, str]]:
    if args.input:
        file_ext = os.path.splitext(args.input)[1].lower()
        if file_ext == ".csv":
            df = pd.read_csv(args.input, dtype=str)
        elif file_ext in [".xls", ".xlsx"]:
            df = pd.read_excel(args.input, dtype=str)
        else:
            raise ValueError(f"Unsupported input file format: {file_ext}")

        df.columns = [col.strip() for col in df.columns]
        required = ["Marketplace", "Zip Code"]
        missing = [col for col in required if col not in df.columns]
        if missing:
            raise ValueError(f"Missing required columns: {', '.join(missing)}")
        if "ASIN" not in df.columns and "Product URL" not in df.columns:
            raise ValueError("Input file must contain either ASIN or Product URL column.")

        df = df.fillna("")
        tasks = []
        for _, row in df.iterrows():
            asin = str(row.get("ASIN", "")).strip()
            product_url = str(row.get("Product URL", "")).strip()
            if not asin and not product_url:
                continue
            tasks.append({
                "marketplace": str(row["Marketplace"]).strip(),
                "zip_code": str(row["Zip Code"]).strip(),
                "asin": asin,
                "product_url": product_url,
            })
        return tasks

    if not args.asin and not args.url:
        raise ValueError("Provide --asin, --url, or --input.")

    return [{
        "marketplace": args.marketplace,
        "zip_code": args.zip_code,
        "asin": args.asin or "",
        "product_url": args.url or "",
    }]


def save_results(results: List[Dict[str, str]]) -> str:
    os.makedirs("results", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"results/detail_page_results_{timestamp}.csv"

    df = pd.DataFrame(results)
    branding_row = {col: "" for col in df.columns}
    if len(df.columns) > 0:
        branding_row[df.columns[0]] = "Generated by Amazon Detailed Page Scrapper - consologist.com"
    df = pd.concat([df, pd.DataFrame([branding_row])], ignore_index=True)
    df.to_csv(filename, index=False)
    return filename


async def run(args):
    tasks = load_detail_tasks(args)
    if not tasks:
        logger.warning("No valid product detail tasks found.")
        return

    browser_manager = BrowserManager(user_data_dir="user_data", headless=args.headless)
    scraper = AmazonDetailScraper(browser_manager)
    results = []
    current_marketplace = None

    try:
        await scraper.initialize()

        for index, task in enumerate(tasks, start=1):
            marketplace = task.get("marketplace") or "amazon.com"
            zip_code = task.get("zip_code") or args.zip_code

            logger.info(f"Processing detail task {index}/{len(tasks)} on {marketplace} for {zip_code}")

            try:
                if current_marketplace != marketplace:
                    current_marketplace = marketplace

                await scraper.go_to_home(marketplace)

                await scraper.set_delivery_zip(zip_code)

                result = await scraper.scrape_product(
                    marketplace=marketplace,
                    zip_code=zip_code,
                    asin=task.get("asin", ""),
                    product_url=task.get("product_url", ""),
                )
                results.append(result)
                logger.info(f"Extracted details for ASIN {result.get('ASIN', '')}")

            except CaptchaDetectedError:
                logger.error("Amazon captcha detected. Solve it in the browser, then rerun this script.")
                break
            except LocationVerificationError as exc:
                logger.error(f"Location error for task {index}: {exc}")
            except Exception as exc:
                logger.error(f"Detail task {index} failed: {exc}", exc_info=True)

            await asyncio.sleep(args.delay)

    finally:
        if results:
            filename = save_results(results)
            logger.info(f"Results saved to {filename}")

        logger.info("Closing browser in 5 seconds...")
        await asyncio.sleep(5)
        await scraper.close()


def parse_args():
    parser = argparse.ArgumentParser(description="Amazon detailed product page scraper")
    parser.add_argument("--marketplace", default="amazon.com", help="Amazon marketplace, e.g. amazon.com or amazon.co.uk")
    parser.add_argument("--zip-code", default="10001", help="Delivery zip/postal code")
    parser.add_argument("--asin", default="", help="Single ASIN to scrape")
    parser.add_argument("--url", default="", help="Single Amazon product URL to scrape")
    parser.add_argument("--input", default="", help="CSV/XLSX with Marketplace, Zip Code, and ASIN or Product URL")
    parser.add_argument("--headless", action="store_true", help="Run browser in headless mode")
    parser.add_argument("--delay", type=float, default=2.0, help="Seconds to wait between product pages")
    return parser.parse_args()


if __name__ == "__main__":
    asyncio.run(run(parse_args()))
